# ==============================================================
# AMBIENTE LOCAL (application-dev.properties)
# ==============================================================
spring.application.name=dev-jobs

# URL de conexão com o banco MySQL local
spring.datasource.url=jdbc:mysql://localhost:3306/devjobs_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234

# Pede para o Hibernate criar/atualizar as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update

# Mostra no console os comandos SQL que o Spring está executando por baixo dos panos
spring.jpa.show-sql=true
